### ISSUE TITLE
Automatic Decryption

### ISSUE THREAD

**Issue by arnoldjp57** [delatbabel/elocryptfive#11]
Hi
I have installed delatbabel/elocryptfive and it encrypts the attributes I specify in the model, but does not decrypt them. What have I missed ....
![image](https://cloud.githubusercontent.com/assets/12873055/13380017/676df292-de3f-11e5-9073-bc85dc14ffa6.png)

**Comment by delatbabel** [comment]
Very strange, it works for me and as per the unit tests.  Show me the code you are using to decrypt?

**Comment by arnoldjp57** [comment]
Ok ... I see why its not decrypting .... I am using DB::table('patns')->where('id',$id)  instead of the eloquent Patn::find($id) ...  Any reason why the DB mechasim does not do the decrypting?

**Comment by delatbabel** [comment]
> Any reason why the DB mechasim does not do the decrypting?

Because it's not supposed to. This package is for Eloquent not for DB.

**Comment by arnoldjp57** [comment]
Ok Cool .... One last question please .... I am trying to decrypt the data on my  view ... 
<td>{{ $patn->decryptedAttribute(surn) }}</td>
I get an error Fatal error: Call to undefined method stdClass::decryptedAttribute() .... 
how do I fix this? Apart from redefining my models and rewriting all my DB::table calls ....  :-) .... 
Is dong the decrypt on the view a reasonable way to go? .... here is a typical DB::goodie

$patn = DB::table('patns')
            ->where('patns.id',$id)
            ->leftJoin('bases as b1', 'patns.titl', '=', 'b1.id')
            ->leftJoin('bases as b2', 'patns.natn', '=', 'b2.id')
            ->select('patns.*', 'b1.desc as titl_desc',
                                'b2.desc as natn_desc')
            ->first();

Going the eloquent route will a big change coz of the namimg .... Going forward, Ill get to grips with the eloquent route.

**Comment by delatbabel** [comment]
No, it's not reasonable to do decryption in the view. The DB class does not have the method decryptedAttribute because it does not use the Elocrypt trait. Using the Eloquent ORM is the only way to use the Elocrypt trait, because you need to attach the trait to your model classes and model classes aren't supported using the DB facade.
