### ISSUE TITLE
php artisan config::publish delatbabel/elocryptfive

### ISSUE THREAD

**Issue by avivronen** [delatbabel/elocryptfive#14]
php artisan config::publish delatbabel/elocryptfive
returning:
←[37;41m                                                             ←[39;49m
←[37;41m  [InvalidArgumentException]                                 ←[39;49m
←[37;41m  There are no commands defined in the "config:" namespace.  ←[39;49m
←[37;41m  Did you mean this?                                         ←[39;49m
←[37;41m      config                                                 ←[39;49m
←[37;41m                                                             ←[39;49m

**Comment by delatbabel** [comment]
It should be config:publish not config::publish

Where did you see the incorrect code?
