### ISSUE TITLE
Concern about losing key

### ISSUE THREAD

**Issue by CHOMNANP** [delatbabel/elocryptfive#15]
Love the way the encryption work. Thank for sharing.

I got a concern. What if I change the server. Then I would regenerate the key "php artisan key:generate" for my new server. How could I recover the encrypted data in the existing database?

Is there any manual way to decrypt the data if I did have my "Key" and "value"?

Thanks.

**Comment by delatbabel** [comment]
> What if I change the server.

Then you should keep the key from your existing server.  If you have lost the key then you can't decrypt the data.  That's what encryption is all about -- preventing someone from decrypting the data if they don't have the key.

> Is there any manual way to decrypt the data if I did have my "Key" and "value"?

Yes, check in the code, look at the decryptedAttribute() method.
