### ISSUE TITLE
vendor:publish problem solved

### ISSUE THREAD

**Issue by shrimpanse** [delatbabel/elocryptfive#21]
I had the same problem as adnanmayo in #16 . Unfortunatly you closed the issue without providing a solution so I thought I provide the solution for all the people like me who are having a problem with this.

Instead of 

`php artisan vendor:publish --provider=Delatbabel\Elocrypt\ElocryptServiceProvider`

you should use

`php artisan vendor:publish --provider='Delatbabel\Elocrypt\ElocryptServiceProvider'`

On some OS (likely windows) you need single quotes around the provider class

**Comment by delatbabel** [comment]
I am surprised to hear that Elocrypt works at all on Windows.  OpenSSL libraries are not natively available on Windows and although there are probably working ports of it via gnuwin32 etc, I wasn't aware that any of them had been integrated into PHP.

I'll adjust the README to note this.
